buffing out update script

diff --git a/update b/update
--- a/update
+++ b/update
@@ -3,9 +3,16 @@
 dir="/bro"
 
 cd "${dir}"
-git_branch="$(cat branch)" && \
-cd "${dir}/git" && \
-git stash && \
-git switch "${git_branch}" && \
-git fetch && \
-git pull
+{ # try
+    echo "Checking for software updates..."
+    
+    ping "github.com" >/dev/null && \
+    git_branch="$(cat branch)" && \
+    cd "${dir}/git" && \
+    git stash && \
+    git switch "${git_branch}" && \
+    git fetch && \
+    git pull
+} || {
+    echo "Error when checking for updates, please check internet connection."
+}
